version: '3.8'

services:
  vulkan-engine:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - .:/workspace:delegated
      - /tmp/.X11-unix:/tmp/.X11-unix
      - build:/workspace/build
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    network_mode: host
    healthcheck:
      test: ["CMD", "xset", "q"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  build: 