version: '3.8'

services:
  vulkan-engine:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    network_mode: host 