if(EXISTS "C:/cpp-vulkan-hip-engine/build_minimal/memory_leak_tests[1]_tests.cmake")
  include("C:/cpp-vulkan-hip-engine/build_minimal/memory_leak_tests[1]_tests.cmake")
else()
  add_test(memory_leak_tests_NOT_BUILT memory_leak_tests_NOT_BUILT)
endif()
