if(EXISTS "C:/cpp-vulkan-hip-engine/build_minimal/unit_tests[1]_tests.cmake")
  include("C:/cpp-vulkan-hip-engine/build_minimal/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
