if(EXISTS "C:/Dev/3DGameOfLife-Vulkan-Edition/3DGameOfLife-Vulkan-Edition/build_e2e_test/unit_tests[1]_tests.cmake")
  include("C:/Dev/3DGameOfLife-Vulkan-Edition/3DGameOfLife-Vulkan-Edition/build_e2e_test/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
