# Hardware configuration for NixOS WSL
# This file is automatically generated by nixos-generate-config

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  # WSL-specific hardware configuration
  boot = {
    # WSL doesn't need a bootloader
    loader.grub.enable = false;
    
    # Use systemd-boot for WSL
    loader.systemd-boot.enable = false;
    
    # Kernel modules for WSL
    kernelModules = [
      "kvm-intel"
      "kvm-amd"
      "virtio"
      "virtio_pci"
      "virtio_net"
      "virtio_blk"
      "virtio_scsi"
      "virtio_balloon"
      "virtio_input"
      "virtio_console"
      "virtio_rng"
      "virtio_gpu"
      "virtio_vsock"
      "virtio_mem"
      "virtio_pmem"
      "virtio_fs"
      "virtio_iommu"
      "virtio_dma_buf"
      "virtio_snd"
      "virtio_video"
      "virtio_crypto"
      "virtio_rpmsg_bus"
      "virtio_rpmsg_char"
      "virtio_watchdog"
      "virtio_pmem"
      "virtio_fs"
      "virtio_iommu"
      "virtio_dma_buf"
      "virtio_snd"
      "virtio_video"
      "virtio_crypto"
      "virtio_rpmsg_bus"
      "virtio_rpmsg_char"
      "virtio_watchdog"
    ];
    
    # Kernel parameters for WSL
    kernelParams = [
      "console=ttyS0"
      "panic=1"
      "boot.panic_on_fail"
      "root=/dev/sda1"
      "ro"
      "quiet"
      "splash"
      "vt.global_cursor_default=0"
      "kvm.ignore_msrs=1"
      "kvm.report_ignored_msrs=0"
    ];
  };

  # File systems
  fileSystems = {
    "/" = {
      device = "/dev/sda1";
      fsType = "ext4";
      options = [ "defaults" "noatime" "nodiratime" ];
    };
    
    "/tmp" = {
      device = "tmpfs";
      fsType = "tmpfs";
      options = [ "defaults" "size=2G" "mode=1777" ];
    };
    
    "/var/tmp" = {
      device = "tmpfs";
      fsType = "tmpfs";
      options = [ "defaults" "size=1G" "mode=1777" ];
    };
  };

  # Swap configuration
  swapDevices = [ ];

  # Hardware configuration
  hardware = {
    # CPU configuration
    cpu = {
      intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
    
    # Enable firmware
    enableRedistributableFirmware = true;
    
    # Graphics configuration for WSL
    opengl = {
      enable = true;
      driSupport = true;
      driSupport32Bit = true;
      extraPackages = with pkgs; [
        vaapiVdpau
        libvdpau-va-gl
      ];
    };
    
    # Audio configuration
    pulseaudio.enable = false; # Use pipewire instead
  };

  # Networking for WSL
  networking = {
    # Use NetworkManager for WSL
    networkmanager.enable = true;
    
    # Disable firewall in WSL
    firewall.enable = false;
    
    # WSL networking configuration
    interfaces = {
      # WSL typically uses eth0
      eth0 = {
        useDHCP = true;
      };
    };
  };

  # System configuration
  system = {
    # State version for WSL
    stateVersion = "23.11";
  };

  # Services configuration
  services = {
    # Enable SSH for remote development
    openssh = {
      enable = true;
      settings = {
        PermitRootLogin = "no";
        PasswordAuthentication = true;
        PubkeyAuthentication = true;
      };
    };
    
    # Enable DBus for desktop integration
    dbus.enable = true;
    
    # Enable PipeWire for audio
    pipewire = {
      enable = true;
      alsa.enable = true;
      pulse.enable = true;
    };
  };

  # Environment configuration
  environment = {
    # System packages for WSL
    systemPackages = with pkgs; [
      # WSL utilities
      wslu
      
      # Basic utilities
      coreutils
      findutils
      gnugrep
      gnused
      gawk
      gnutar
      gzip
      bzip2
      xz
      zip
      unzip
      
      # Network utilities
      inetutils
      iputils
      netcat
      socat
      
      # Process utilities
      procps
      psmisc
      htop
      iotop
      
      # File system utilities
      e2fsprogs
      f2fs-tools
      dosfstools
      ntfs3g
      
      # System information
      lshw
      pciutils
      usbutils
      dmidecode
      
      # Development utilities
      gdb
      strace
      ltrace
      valgrind
      perf-tools
    ];
  };

  # Security configuration
  security = {
    # Audit configuration
    auditd.enable = true;
    
    # Sudo configuration
    sudo = {
      enable = true;
      wheelNeedsPassword = false;
    };
  };

  # Users configuration
  users = {
    # Default user for WSL
    defaultUserShell = pkgs.zsh;
    
    # Groups
    groups = {
      vulkan-dev = {
        gid = 1000;
      };
      video = {
        gid = 44;
      };
      audio = {
        gid = 29;
      };
    };
  };
} 